/**
 * Generert fra scripts/*.sql — IKKE rediger for hånd, generer på nytt fra
 * kildefilene hvis en migrering endres.
 * Brukes av /api/admin/deploy-migration (SEED_SECRET) til å kjøre migreringene
 * fra app-en selv, siden prod-DB-en er brannmurslåst mot ekstern SQL-tilgang.
 */

export const MIGRATIONS: { name: string; statements: string[] }[] = [
  {
    name: 'crm',
    statements: [
      "CREATE TABLE \"organizations\" (\n    \"id\" SERIAL NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"org_number\" TEXT,\n    \"domain\" TEXT,\n    \"phone\" TEXT,\n    \"address\" TEXT,\n    \"owner_id\" INTEGER,\n    \"stage\" TEXT NOT NULL DEFAULT 'lead',\n    \"tags\" TEXT NOT NULL DEFAULT '[]',\n    \"custom_fields\" TEXT NOT NULL DEFAULT '{}',\n    \"last_activity_at\" TIMESTAMP(3),\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"organizations_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"contacts\" (\n    \"id\" SERIAL NOT NULL,\n    \"email\" TEXT,\n    \"name\" TEXT NOT NULL,\n    \"phone\" TEXT,\n    \"organization_id\" INTEGER,\n    \"role_title\" TEXT,\n    \"user_id\" INTEGER,\n    \"parent_id\" INTEGER,\n    \"source\" TEXT NOT NULL DEFAULT 'manual',\n    \"owner_id\" INTEGER,\n    \"stage\" TEXT NOT NULL DEFAULT 'lead',\n    \"tags\" TEXT NOT NULL DEFAULT '[]',\n    \"custom_fields\" TEXT NOT NULL DEFAULT '{}',\n    \"last_activity_at\" TIMESTAMP(3),\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"contacts_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"contact_lists\" (\n    \"id\" SERIAL NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"contact_lists_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"contact_list_memberships\" (\n    \"id\" SERIAL NOT NULL,\n    \"list_id\" INTEGER NOT NULL,\n    \"contact_id\" INTEGER NOT NULL,\n    \"added_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"contact_list_memberships_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"segments\" (\n    \"id\" SERIAL NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"rules\" TEXT NOT NULL DEFAULT '{}',\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"segments_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"pipelines\" (\n    \"id\" SERIAL NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"pipelines_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"stages\" (\n    \"id\" SERIAL NOT NULL,\n    \"pipeline_id\" INTEGER NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"position\" INTEGER NOT NULL DEFAULT 0,\n    \"is_won\" BOOLEAN NOT NULL DEFAULT false,\n    \"is_lost\" BOOLEAN NOT NULL DEFAULT false,\n\n    CONSTRAINT \"stages_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"deals\" (\n    \"id\" SERIAL NOT NULL,\n    \"title\" TEXT NOT NULL,\n    \"pipeline_id\" INTEGER NOT NULL,\n    \"stage_id\" INTEGER NOT NULL,\n    \"contact_id\" INTEGER,\n    \"organization_id\" INTEGER,\n    \"owner_id\" INTEGER,\n    \"value\" DOUBLE PRECISION,\n    \"probability\" INTEGER,\n    \"event_type\" TEXT,\n    \"event_date\" TIMESTAMP(3),\n    \"status\" TEXT NOT NULL DEFAULT 'open',\n    \"closed_at\" TIMESTAMP(3),\n    \"source\" TEXT NOT NULL DEFAULT 'manual',\n    \"booking_request_id\" INTEGER,\n    \"registration_id\" INTEGER,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"deals_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"contact_activities\" (\n    \"id\" SERIAL NOT NULL,\n    \"contact_id\" INTEGER,\n    \"organization_id\" INTEGER,\n    \"type\" TEXT NOT NULL,\n    \"title\" TEXT NOT NULL,\n    \"body\" TEXT,\n    \"meta\" TEXT NOT NULL DEFAULT '{}',\n    \"actor_email\" TEXT,\n    \"occurred_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"contact_activities_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"tasks\" (\n    \"id\" SERIAL NOT NULL,\n    \"title\" TEXT NOT NULL,\n    \"contact_id\" INTEGER,\n    \"organization_id\" INTEGER,\n    \"deal_id\" INTEGER,\n    \"assignee_id\" INTEGER,\n    \"due_at\" TIMESTAMP(3),\n    \"status\" TEXT NOT NULL DEFAULT 'open',\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"tasks_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"notes\" (\n    \"id\" SERIAL NOT NULL,\n    \"body\" TEXT NOT NULL,\n    \"contact_id\" INTEGER,\n    \"organization_id\" INTEGER,\n    \"deal_id\" INTEGER,\n    \"author_email\" TEXT NOT NULL,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"notes_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"consents\" (\n    \"id\" SERIAL NOT NULL,\n    \"contact_id\" INTEGER NOT NULL,\n    \"marketing\" BOOLEAN NOT NULL DEFAULT false,\n    \"lawful_basis\" TEXT,\n    \"consent_at\" TIMESTAMP(3),\n    \"source\" TEXT,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"consents_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"suppressions\" (\n    \"id\" SERIAL NOT NULL,\n    \"email\" TEXT NOT NULL,\n    \"reason\" TEXT NOT NULL DEFAULT 'unsubscribe',\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"suppressions_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE UNIQUE INDEX \"organizations_domain_key\" ON \"organizations\"(\"domain\")",
      "CREATE INDEX \"organizations_stage_idx\" ON \"organizations\"(\"stage\")",
      "CREATE UNIQUE INDEX \"contacts_email_key\" ON \"contacts\"(\"email\")",
      "CREATE UNIQUE INDEX \"contacts_user_id_key\" ON \"contacts\"(\"user_id\")",
      "CREATE INDEX \"contacts_organization_id_idx\" ON \"contacts\"(\"organization_id\")",
      "CREATE INDEX \"contacts_stage_idx\" ON \"contacts\"(\"stage\")",
      "CREATE INDEX \"contacts_parent_id_idx\" ON \"contacts\"(\"parent_id\")",
      "CREATE INDEX \"contact_list_memberships_contact_id_idx\" ON \"contact_list_memberships\"(\"contact_id\")",
      "CREATE UNIQUE INDEX \"contact_list_memberships_list_id_contact_id_key\" ON \"contact_list_memberships\"(\"list_id\", \"contact_id\")",
      "CREATE UNIQUE INDEX \"pipelines_name_key\" ON \"pipelines\"(\"name\")",
      "CREATE INDEX \"stages_pipeline_id_idx\" ON \"stages\"(\"pipeline_id\")",
      "CREATE UNIQUE INDEX \"deals_booking_request_id_key\" ON \"deals\"(\"booking_request_id\")",
      "CREATE UNIQUE INDEX \"deals_registration_id_key\" ON \"deals\"(\"registration_id\")",
      "CREATE INDEX \"deals_pipeline_id_stage_id_idx\" ON \"deals\"(\"pipeline_id\", \"stage_id\")",
      "CREATE INDEX \"deals_contact_id_idx\" ON \"deals\"(\"contact_id\")",
      "CREATE INDEX \"deals_organization_id_idx\" ON \"deals\"(\"organization_id\")",
      "CREATE INDEX \"deals_event_type_event_date_idx\" ON \"deals\"(\"event_type\", \"event_date\")",
      "CREATE INDEX \"contact_activities_contact_id_occurred_at_idx\" ON \"contact_activities\"(\"contact_id\", \"occurred_at\")",
      "CREATE INDEX \"contact_activities_organization_id_occurred_at_idx\" ON \"contact_activities\"(\"organization_id\", \"occurred_at\")",
      "CREATE INDEX \"tasks_assignee_id_status_idx\" ON \"tasks\"(\"assignee_id\", \"status\")",
      "CREATE INDEX \"tasks_contact_id_idx\" ON \"tasks\"(\"contact_id\")",
      "CREATE INDEX \"tasks_organization_id_idx\" ON \"tasks\"(\"organization_id\")",
      "CREATE INDEX \"tasks_deal_id_idx\" ON \"tasks\"(\"deal_id\")",
      "CREATE INDEX \"notes_contact_id_idx\" ON \"notes\"(\"contact_id\")",
      "CREATE INDEX \"notes_organization_id_idx\" ON \"notes\"(\"organization_id\")",
      "CREATE INDEX \"notes_deal_id_idx\" ON \"notes\"(\"deal_id\")",
      "CREATE UNIQUE INDEX \"consents_contact_id_key\" ON \"consents\"(\"contact_id\")",
      "CREATE UNIQUE INDEX \"suppressions_email_key\" ON \"suppressions\"(\"email\")",
      "ALTER TABLE \"organizations\" ADD CONSTRAINT \"organizations_owner_id_fkey\" FOREIGN KEY (\"owner_id\") REFERENCES \"users\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"contacts\" ADD CONSTRAINT \"contacts_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organizations\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"contacts\" ADD CONSTRAINT \"contacts_owner_id_fkey\" FOREIGN KEY (\"owner_id\") REFERENCES \"users\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"contacts\" ADD CONSTRAINT \"contacts_user_id_fkey\" FOREIGN KEY (\"user_id\") REFERENCES \"users\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"contacts\" ADD CONSTRAINT \"contacts_parent_id_fkey\" FOREIGN KEY (\"parent_id\") REFERENCES \"parents\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"contact_list_memberships\" ADD CONSTRAINT \"contact_list_memberships_list_id_fkey\" FOREIGN KEY (\"list_id\") REFERENCES \"contact_lists\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"contact_list_memberships\" ADD CONSTRAINT \"contact_list_memberships_contact_id_fkey\" FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"stages\" ADD CONSTRAINT \"stages_pipeline_id_fkey\" FOREIGN KEY (\"pipeline_id\") REFERENCES \"pipelines\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"deals\" ADD CONSTRAINT \"deals_pipeline_id_fkey\" FOREIGN KEY (\"pipeline_id\") REFERENCES \"pipelines\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"deals\" ADD CONSTRAINT \"deals_stage_id_fkey\" FOREIGN KEY (\"stage_id\") REFERENCES \"stages\"(\"id\") ON DELETE RESTRICT ON UPDATE CASCADE",
      "ALTER TABLE \"deals\" ADD CONSTRAINT \"deals_contact_id_fkey\" FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"deals\" ADD CONSTRAINT \"deals_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organizations\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"deals\" ADD CONSTRAINT \"deals_owner_id_fkey\" FOREIGN KEY (\"owner_id\") REFERENCES \"users\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"contact_activities\" ADD CONSTRAINT \"contact_activities_contact_id_fkey\" FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"contact_activities\" ADD CONSTRAINT \"contact_activities_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organizations\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"tasks\" ADD CONSTRAINT \"tasks_contact_id_fkey\" FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"tasks\" ADD CONSTRAINT \"tasks_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organizations\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"tasks\" ADD CONSTRAINT \"tasks_deal_id_fkey\" FOREIGN KEY (\"deal_id\") REFERENCES \"deals\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"tasks\" ADD CONSTRAINT \"tasks_assignee_id_fkey\" FOREIGN KEY (\"assignee_id\") REFERENCES \"users\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"notes\" ADD CONSTRAINT \"notes_contact_id_fkey\" FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"notes\" ADD CONSTRAINT \"notes_organization_id_fkey\" FOREIGN KEY (\"organization_id\") REFERENCES \"organizations\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"notes\" ADD CONSTRAINT \"notes_deal_id_fkey\" FOREIGN KEY (\"deal_id\") REFERENCES \"deals\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"consents\" ADD CONSTRAINT \"consents_contact_id_fkey\" FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
    ],
  },
  {
    name: 'event-bus',
    statements: [
      "CREATE TABLE \"visitors\" (\n    \"id\" SERIAL NOT NULL,\n    \"public_id\" TEXT NOT NULL,\n    \"contact_id\" INTEGER,\n    \"first_seen_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"last_seen_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"visitors_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"app_events\" (\n    \"id\" SERIAL NOT NULL,\n    \"type\" TEXT NOT NULL,\n    \"source\" TEXT NOT NULL,\n    \"contact_id\" INTEGER,\n    \"visitor_id\" INTEGER,\n    \"meta\" TEXT NOT NULL DEFAULT '{}',\n    \"dedupe_key\" TEXT,\n    \"occurred_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"app_events_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE UNIQUE INDEX \"visitors_public_id_key\" ON \"visitors\"(\"public_id\")",
      "CREATE INDEX \"visitors_contact_id_idx\" ON \"visitors\"(\"contact_id\")",
      "CREATE UNIQUE INDEX \"app_events_dedupe_key_key\" ON \"app_events\"(\"dedupe_key\")",
      "CREATE INDEX \"app_events_type_idx\" ON \"app_events\"(\"type\")",
      "CREATE INDEX \"app_events_contact_id_occurred_at_idx\" ON \"app_events\"(\"contact_id\", \"occurred_at\")",
      "CREATE INDEX \"app_events_visitor_id_occurred_at_idx\" ON \"app_events\"(\"visitor_id\", \"occurred_at\")",
      "CREATE INDEX \"app_events_occurred_at_idx\" ON \"app_events\"(\"occurred_at\")",
      "ALTER TABLE \"visitors\" ADD CONSTRAINT \"visitors_contact_id_fkey\" FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"app_events\" ADD CONSTRAINT \"app_events_contact_id_fkey\" FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "ALTER TABLE \"app_events\" ADD CONSTRAINT \"app_events_visitor_id_fkey\" FOREIGN KEY (\"visitor_id\") REFERENCES \"visitors\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
    ],
  },
  {
    name: 'payments',
    statements: [
      "ALTER TABLE \"booking_requests\" ADD COLUMN     \"payment_intent_ref\" TEXT,\nADD COLUMN     \"payment_provider\" TEXT,\nADD COLUMN     \"payment_ref\" TEXT,\nADD COLUMN     \"payment_status\" TEXT NOT NULL DEFAULT 'none'",
      "ALTER TABLE \"registrations\" ADD COLUMN     \"payment_intent_ref\" TEXT,\nADD COLUMN     \"payment_provider\" TEXT,\nADD COLUMN     \"payment_ref\" TEXT,\nADD COLUMN     \"payment_status\" TEXT NOT NULL DEFAULT 'none'",
      "CREATE UNIQUE INDEX \"booking_requests_payment_ref_key\" ON \"booking_requests\"(\"payment_ref\")",
      "CREATE UNIQUE INDEX \"booking_requests_payment_intent_ref_key\" ON \"booking_requests\"(\"payment_intent_ref\")",
      "CREATE UNIQUE INDEX \"registrations_payment_ref_key\" ON \"registrations\"(\"payment_ref\")",
      "CREATE UNIQUE INDEX \"registrations_payment_intent_ref_key\" ON \"registrations\"(\"payment_intent_ref\")",
    ],
  },
  {
    name: 'flow-engine',
    statements: [
      "CREATE TABLE \"flows\" (\n    \"id\" SERIAL NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"description\" TEXT,\n    \"status\" TEXT NOT NULL DEFAULT 'draft',\n    \"is_marketing\" BOOLEAN NOT NULL DEFAULT true,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"flows_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"flow_nodes\" (\n    \"id\" SERIAL NOT NULL,\n    \"flow_id\" INTEGER NOT NULL,\n    \"type\" TEXT NOT NULL,\n    \"config\" TEXT NOT NULL DEFAULT '{}',\n    \"pos_x\" DOUBLE PRECISION NOT NULL DEFAULT 0,\n    \"pos_y\" DOUBLE PRECISION NOT NULL DEFAULT 0,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"flow_nodes_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"flow_edges\" (\n    \"id\" SERIAL NOT NULL,\n    \"flow_id\" INTEGER NOT NULL,\n    \"from_node_id\" INTEGER NOT NULL,\n    \"to_node_id\" INTEGER NOT NULL,\n    \"branch\" TEXT,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"flow_edges_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"flow_triggers\" (\n    \"id\" SERIAL NOT NULL,\n    \"flow_id\" INTEGER NOT NULL,\n    \"event_type\" TEXT NOT NULL,\n    \"filter\" TEXT NOT NULL DEFAULT '{}',\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"flow_triggers_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"flow_enrollments\" (\n    \"id\" SERIAL NOT NULL,\n    \"flow_id\" INTEGER NOT NULL,\n    \"contact_id\" INTEGER NOT NULL,\n    \"current_node_id\" INTEGER,\n    \"status\" TEXT NOT NULL DEFAULT 'active',\n    \"next_run_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"entered_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"finished_at\" TIMESTAMP(3),\n    \"fail_reason\" TEXT,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"flow_enrollments_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"sender_identities\" (\n    \"id\" SERIAL NOT NULL,\n    \"email\" TEXT NOT NULL,\n    \"display_name\" TEXT NOT NULL,\n    \"active\" BOOLEAN NOT NULL DEFAULT true,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"sender_identities_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE TABLE \"message_sends\" (\n    \"id\" SERIAL NOT NULL,\n    \"enrollment_id\" INTEGER,\n    \"node_id\" INTEGER,\n    \"contact_id\" INTEGER NOT NULL,\n    \"sender_identity_id\" INTEGER,\n    \"to_email\" TEXT NOT NULL,\n    \"subject\" TEXT NOT NULL,\n    \"body_html\" TEXT NOT NULL,\n    \"status\" TEXT NOT NULL DEFAULT 'sent',\n    \"dedupe_key\" TEXT,\n    \"sent_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"message_sends_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE INDEX \"flow_nodes_flow_id_idx\" ON \"flow_nodes\"(\"flow_id\")",
      "CREATE INDEX \"flow_edges_flow_id_idx\" ON \"flow_edges\"(\"flow_id\")",
      "CREATE INDEX \"flow_triggers_event_type_idx\" ON \"flow_triggers\"(\"event_type\")",
      "CREATE INDEX \"flow_enrollments_status_next_run_at_idx\" ON \"flow_enrollments\"(\"status\", \"next_run_at\")",
      "CREATE INDEX \"flow_enrollments_flow_id_contact_id_status_idx\" ON \"flow_enrollments\"(\"flow_id\", \"contact_id\", \"status\")",
      "CREATE UNIQUE INDEX \"sender_identities_email_key\" ON \"sender_identities\"(\"email\")",
      "CREATE UNIQUE INDEX \"message_sends_dedupe_key_key\" ON \"message_sends\"(\"dedupe_key\")",
      "CREATE INDEX \"message_sends_contact_id_sent_at_idx\" ON \"message_sends\"(\"contact_id\", \"sent_at\")",
      "ALTER TABLE \"flow_nodes\" ADD CONSTRAINT \"flow_nodes_flow_id_fkey\" FOREIGN KEY (\"flow_id\") REFERENCES \"flows\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"flow_edges\" ADD CONSTRAINT \"flow_edges_flow_id_fkey\" FOREIGN KEY (\"flow_id\") REFERENCES \"flows\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"flow_triggers\" ADD CONSTRAINT \"flow_triggers_flow_id_fkey\" FOREIGN KEY (\"flow_id\") REFERENCES \"flows\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"flow_enrollments\" ADD CONSTRAINT \"flow_enrollments_flow_id_fkey\" FOREIGN KEY (\"flow_id\") REFERENCES \"flows\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"flow_enrollments\" ADD CONSTRAINT \"flow_enrollments_contact_id_fkey\" FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"message_sends\" ADD CONSTRAINT \"message_sends_contact_id_fkey\" FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
      "ALTER TABLE \"message_sends\" ADD CONSTRAINT \"message_sends_sender_identity_id_fkey\" FOREIGN KEY (\"sender_identity_id\") REFERENCES \"sender_identities\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
      "CREATE UNIQUE INDEX IF NOT EXISTS \"flow_enrollments_one_active\" ON \"flow_enrollments\"(\"flow_id\",\"contact_id\") WHERE status = 'active'",
    ],
  },
  {
    name: 'email-tracking',
    statements: [
      "ALTER TABLE \"message_sends\" ADD COLUMN     \"bounced_at\" TIMESTAMP(3),\nADD COLUMN     \"click_count\" INTEGER NOT NULL DEFAULT 0,\nADD COLUMN     \"first_clicked_at\" TIMESTAMP(3),\nADD COLUMN     \"message_id\" TEXT,\nADD COLUMN     \"opened_at\" TIMESTAMP(3),\nADD COLUMN     \"replied_at\" TIMESTAMP(3),\nADD COLUMN     \"tracking_token\" TEXT",
      "CREATE TABLE \"message_links\" (\n    \"id\" SERIAL NOT NULL,\n    \"message_send_id\" INTEGER NOT NULL,\n    \"idx\" INTEGER NOT NULL,\n    \"url\" TEXT NOT NULL,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"message_links_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE UNIQUE INDEX \"message_links_message_send_id_idx_key\" ON \"message_links\"(\"message_send_id\", \"idx\")",
      "CREATE UNIQUE INDEX \"message_sends_tracking_token_key\" ON \"message_sends\"(\"tracking_token\")",
      "CREATE INDEX \"message_sends_message_id_idx\" ON \"message_sends\"(\"message_id\")",
      "ALTER TABLE \"message_links\" ADD CONSTRAINT \"message_links_message_send_id_fkey\" FOREIGN KEY (\"message_send_id\") REFERENCES \"message_sends\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
    ],
  },
  {
    name: 'ai-layer',
    statements: [
      "ALTER TABLE \"message_sends\" ADD COLUMN     \"ai_personalized\" BOOLEAN NOT NULL DEFAULT false",
      "CREATE TABLE \"ai_suggestions\" (\n    \"id\" SERIAL NOT NULL,\n    \"flow_id\" INTEGER NOT NULL,\n    \"kind\" TEXT NOT NULL,\n    \"title\" TEXT NOT NULL,\n    \"detail\" TEXT NOT NULL,\n    \"status\" TEXT NOT NULL DEFAULT 'open',\n    \"dedupe_key\" TEXT NOT NULL,\n    \"created_at\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updated_at\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"ai_suggestions_pkey\" PRIMARY KEY (\"id\")\n)",
      "CREATE UNIQUE INDEX \"ai_suggestions_dedupe_key_key\" ON \"ai_suggestions\"(\"dedupe_key\")",
      "CREATE INDEX \"ai_suggestions_flow_id_status_idx\" ON \"ai_suggestions\"(\"flow_id\", \"status\")",
      "ALTER TABLE \"ai_suggestions\" ADD CONSTRAINT \"ai_suggestions_flow_id_fkey\" FOREIGN KEY (\"flow_id\") REFERENCES \"flows\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
    ],
  },
  {
    name: 'course-flows',
    statements: [
      "ALTER TABLE flow_enrollments ADD COLUMN IF NOT EXISTS course_id INT NULL",
      "ALTER TABLE flow_enrollments ADD COLUMN IF NOT EXISTS registration_id INT NULL",
      "ALTER TABLE flow_enrollments DROP CONSTRAINT IF EXISTS flow_enrollments_course_id_fkey",
      "ALTER TABLE flow_enrollments\n  ADD CONSTRAINT flow_enrollments_course_id_fkey\n  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL",
      "ALTER TABLE flow_enrollments DROP CONSTRAINT IF EXISTS flow_enrollments_registration_id_fkey",
      "ALTER TABLE flow_enrollments\n  ADD CONSTRAINT flow_enrollments_registration_id_fkey\n  FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE CASCADE",
      "CREATE INDEX IF NOT EXISTS flow_enrollments_registration_id_idx ON flow_enrollments (registration_id)",
      "CREATE INDEX IF NOT EXISTS flow_enrollments_course_id_idx ON flow_enrollments (course_id)",
      "DROP INDEX IF EXISTS flow_enrollments_one_active",
      "CREATE UNIQUE INDEX flow_enrollments_one_active\n  ON flow_enrollments (flow_id, contact_id)\n  WHERE registration_id IS NULL AND status = 'active'",
      "CREATE UNIQUE INDEX IF NOT EXISTS flow_enrollments_one_active_reg\n  ON flow_enrollments (flow_id, registration_id)\n  WHERE registration_id IS NOT NULL AND status = 'active'",
    ],
  },
  {
    name: 'course-lifecycle',
    statements: [
      "ALTER TABLE flows ADD COLUMN IF NOT EXISTS anchor_mode TEXT NOT NULL DEFAULT 'contact'",
    ],
  },
];
